### ISSUE TITLE
User Can Create a Town

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/ajax-project#1]
## 💰 Motivation

Animal Crossing New Horizons Player will want to track their town progress and events.

## 📐 Plan

Create a responsive form that allows users to store an image URL with pertinent information about their town.

## 🖼️ Wireframes

![User-can-create-a-town-phone-view](https://user-images.githubusercontent.com/105157437/192360305-5616f399-2799-4b15-98e9-4428153568c5.png)
![User-can-create-a-town-desktop-view](https://user-images.githubusercontent.com/105157437/192360309-634623fd-be58-4555-8b1a-5ce0f7963e49.png)

## ✅ Task List

- [x] Add a `div[data-view="town-entry-form"]` to the HTML.
- [x] Add a form for creating a journal entry to the `div[data-view="town-entry-form"]`.
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [x] Make all inputs of the journal entry form `required`.
- [x] Listen for `click` events on the `fruitSelection` input to update the currently selected fruit & radiobutton.
- [x] Add a function to handle image inputs 
- [x] Add a villager selection button with an event listener for `'click'` events. 
  - [x] Create a function that calls the ACNH Hapi API and returns an array of villager objects with the villager names and icons. 
  - [x] On click, pull up an input field with all villagers preloaded using the names from the previous object.
  - [x] Add an `'add'` button with an event listener for `'click'` events.
    - [x] On click, add the villager to the `'current-villager'` array in data.js"
    - [x] Add a function that renders a villager icon with a gray background circle.
    - [x] Call this function whenever the `'add'` button is clicked, rendering the villager that user just added. 
- [x] Listen for `'submit'` events on the journal entry form and:
  - [x] Put the form's input values into a new object.
  - [x] Put the `current-villager` array into the same object. 
  - [x] Add the `nextEntryId` to the object.
  - [x] Increment the `nextEntryId` on the data model.
  - [x] Prepend the new object to the entries in the data model.
  - [x] Reset the image preview's `src` attribute.
  - [x] Reset the form inputs.
- [x] Verify that new entries are saved to local storage in the `towns` array along with the rest of the data model on page reload.
- [x] Verify that each new entry receives an incrementing `entryId`.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
