### ISSUE TITLE
Bug: Mobile Screens under 400 px have the following issues

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/ajax-project#14]
## ✅ Task List

- [x] Home page default message ("No towns have been recorded yet") is flush with `add Town` button.
- [x] In the `town-entry-form` view...
  - [x] The radio button beneath each fruit is not centered.
  - [x] The plus sign beneath `Current Villagers` is not centered. 
  - [x] The input box beneath the plus sign is too short. It should take up the remaining width of the screen.
- [x] In the `town-home-page` view... 
  - [x] The fruit at the top of the page needs some padding to the right
  - [x] The events section of daily news is overflowing beyond the width of the page.
    - [x] Shorten the text of each event description to fit one line. Add ellipses to show further text is **present.** 
  - [x] The collection image icons are too large.
  - [x] The collections section is also overflowing the page. This is likely due to the width exceeding 100% for that row. Fix it!
- [x] In the `collections` view... 
  - [x] The fruit at the top of the page needs some padding to the right
  - [x] The collection image icons are too large here as well.
  - [x] The` collections section` is also overflowing the page as well. This is likely due to the width exceeding 100% for that row. Fix it!
  - [x] The` collections modal` has a few issues...
    - [x] The location text is slightly cut off on the right side.
    - [x] The number associated with shadow size is not aligned properly to the top left corner.
    - [x] The `borders` surrounding the months for the Seasonality section are boxes instead of flush with each month.
