### ISSUE TITLE
Feature: User can view the About page

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/ajax-project#16]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to view usage information about the app and reach out with any bugs they found / other contact info.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add photo of personal animal crossing town.
- [x] Add personal note section about webpage.
- [x] Add pictures with detailed information about how to create a town and interact with the website.
- [x] Make it all look great with spacing and box-shadow -- CSS!
