### ISSUE TITLE
User Can View Their Towns

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/ajax-project#2]
## 💰 Motivation

Once a user uploads their town data, they'll want to see their entered information.

## 📐 Plan

Display the user's journal entries in reverse chronological order so they can see the newest ones first. 

## 🖼️ Wireframes

![user-can-view-all-towns-phone-view](https://user-images.githubusercontent.com/105157437/192361560-90f03462-96be-4b34-bd91-2937bd2f56bf.png)
![user-can-view-all-towns-desktop-view](https://user-images.githubusercontent.com/105157437/192361561-f68829a0-a9d2-408f-a5bc-4c35d8cdef93.png)

## ✅ Task List

- [x] Add a sibling `div[data-view="town-entries"]` to the HTML.
- [x] Add an empty unordered list to the `div[data-view="town-entries"]` element in the HTML.
- [x] Add some dummy towns to the unordered list in the HTML and style them to match the wireframe.
- [x] Check that the entries list looks good on both mobile and desktop screens.
- [x] Define a function that takes a single `town-entry` object and returns a DOM tree that matches one of the example entries in the HTML.
- [x] Use a loop to create a DOM tree for each journal entry in the data model and append it to the page when the `'DOMContentLoaded'` event is fired.
- [x] Remove the example HTML entries once the user's entries are successfully being appended to the DOM on page load.
- [x] Add a navigation item to the navbar for Towns.
- [x] Add an anchor to the entries view that shows the entry form.
- [x] Ensure that submitting a new journal entry also creates a new DOM tree for it and adds it to the page.
- [x] Ensure that submitting a new journal entry automatically shows the `'town-entries'` view without reloading the page.
- [x] Ensure that refreshing the pages shows the same view as before refreshing.
- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
