### ISSUE TITLE
Bug: Some fish images are not rendering

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/ajax-project#26]
#### Desired Behavior

> ##### The app should ...

All fish images should render appropriately when clicked.

#### Actual Behavior

> ##### The app does this instead ...

Some fish (freshwater goby and others) do not render an image when clicked within `collections`.

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

Go into collections on a newly created town and click on `freshwater goby`. The image is missing.

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [ ] Image is missing from API call so reach out to Nookipedia and ask about possible missing data.
- **Clean Up**
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
