### ISSUE TITLE
Bug: Hamburger Menu Disappears at 768px

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/ajax-project#27]
#### Desired Behavior

> ##### The app should ...

Either a hamburger menu or a regular menu should appear for users to navigate the site at 768px.

#### Actual Behavior

> ##### The app does this instead ...

Instead, the navbar appears empty (no hamburger menu or regular navigation links).

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

Either access the site on a tablet with 768px width or change your screen size to that width within the browser.

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [ ] Change media queries so that mobile mode is the default `view` for users. At larger screen sizes, additional css should apply.
- [ ] ...
- **Clean Up**
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
