### ISSUE TITLE
User Can View Their Town's Home Page

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/ajax-project#3]
## 💰 Motivation

After a user creates their town, they'll want to see current event information and collection status for their town.

## 📐 Plan

Display the user's town data, current event information, and collection status on a home page.

## 🖼️ Wireframes

![user-can-view-all-their-home-page-phone](https://user-images.githubusercontent.com/105157437/192363127-826229ad-cf27-4e32-8fca-9685bba24f9d.png)
![user-can-view-all-their-home-page-desktop](https://user-images.githubusercontent.com/105157437/192363128-e354a9f4-5595-4f6a-b7ca-5839cc4dc145.png)

## ✅ Task List

- [x] Add a sibling `div[data-view="town-home-page"]` to the HTML.
- [x] Add a function that grabs today's date and displays it at the top of the page alongside the user's town fruit.
- [x] Add three sections under the `div[data-view="town-home-page"]` in the HTML. Daily News Birthday, Quotes, & Events.
- [x] For each of these three sections...
  - [x] Add some dummy data to the `div` and style it to match the wireframe for the user-entered town data.
  - [x] Check that the display looks good on both mobile and desktop screens.
 
Following is the information that needs added to these three sections unique to each town.
- [x] For the "town-information" section...
  - [x] Use the same structure from the home page, but for the mobile version, make sure the villagers are appended below.
- [x] For the "daily-news" section...
  - [x] Add a villager birthday key / value pair to the stored villagers inside the town object.
  - [x] Create a function to return T / F that checks for villager birthdays. 
  - [x] If a villager has a birthday, append their icon to the birthdays section.
  - [x] Create a function that grabs the next week of dates and stores them in an array.
  - [x] When calling the API on window load, return a list of events for the next two months.
    - [x] Create a function that renders events similar to the wireframe. 
    - [x] If an event is currently going OR occurs within the next week, feed that event into the renderEvent function and append it to the page.
  - [x] Define a new `function` that accesses a quotes object and returns a random quote. Append to page.
- [x] For the "collections" section... --> nothing needed yet! (whew)

Once all of that is set-up, we need to make sure that we grab the correct town from the "town-entries" page.
- [x] Add an event listener for click events to the 'Jump back in!' button on the "town-entries" page.
  - [x] Ensure each town has a unique data-entry-id attribute with it's respective unique numeric value. 
  - [x] Iterate through all towns in the data model, and pull the town with the matching entryID.
  - [x] Pass that town's data into the relevant functions above and switch to the data-view `town-home-page`
  - [x] Ensure that default messages appear if sections are otherwise empty.
 
Final Touches...
- [x] Add an `a` tag to the navbar for "home" and make sure it directs the user to the most recently accessed home-page.
- [x] Ensure that on refresh, the home-page re-renders correctly. 
- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
