### ISSUE TITLE
Bug: When the user does not upload a town photo, the app loads a blank picture on subsequent reloads

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/ajax-project#37]
#### Desired Behavior

> ##### The app should ...

If the user does not upload a photo, the app should use the default Tommy and Timmy photo for their profile page.

#### Actual Behavior

> ##### The app does this instead ...

The app uses the placeholder image on first load, and then on subsequent loads renders a blank picture.

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

Complete the `create-town` form without uploading a picture and then reopen the app after closing your browser.

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [ ] Add the default Tommy and Timmy photo to `photos`.
- [ ] Within the `create-town` form --> add logic to catch when user does not upload a photo
  - [ ] When this happens, the Tommy and Timmy default photo should be used instead of the placeholder.
- **Clean Up**
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
