### ISSUE TITLE
User Can Edit Town Information

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/ajax-project#4]
## 💰 Motivation

If a user needs to edit their town (most likely the villagers), they need to be able to do so.

## 📐 Plan

Add an edit button that reopens the create new town screen with prefilled information and allows the user to edit that data.

## 🖼️ Wireframes

![User-can-edit-their-town-information-phone](https://user-images.githubusercontent.com/105157437/192380509-f7b7209a-a0ab-4940-a2d7-ced8d2ab8f34.png)
![User-can-edit-their-town-information-desktop](https://user-images.githubusercontent.com/105157437/192380510-f5a132bc-930c-4934-9f55-487ef72db275.png)

## ✅ Task List

- [x] Update "town-home-page" HTML to include an edit icon.
- [x] Listen for clicks on the edit icon.
- [x] Show the entry form if an edit icon was clicked.
- [x] Assign the currently opened town `data.currentTown` to the data model's `editing` property.
- [x] Add `button` for removing villagers and add event listener for `click` events on `button`.
- [x] Create a function that removes a villager from the current villager list and the DOM of the entry page. Call this function when the remove `button` is clicked.
- [x] Pre-populate the town-form with its current values.
- [x] Update the town form's submit handler function to update the existing data in "towns".
- [x] Update the town form's submit handler function to replace the existing "town-information" and "daily-news" `divs`.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
