### ISSUE TITLE
User Can View the Critterpedia

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/ajax-project#5]
## 💰 Motivation

Users will want to view the critterpedia.

## 📐 Plan

Pull relevant data from the API for all collections, and use that data to render tables with all collection data.

## 🖼️ Wireframes

![user-can-view-collections](https://user-images.githubusercontent.com/105157437/192400481-195f6178-c1c7-4ed8-abe8-600ae17c00a9.png)
![user-can-view-collections-desktop](https://user-images.githubusercontent.com/105157437/192400480-199ae741-c3b4-4180-ac91-7df81de64a2a.png)

## ✅ Task List

- [x] Add 5 sibling `div[data-view="collections"]` to the HTML.
- [x] Type each collection --> "fish-collection", "bug-collection", "fossil-collection", "sea-collection", and "art-collection".
- [x] Using some dummy data, match the display of the wireframe.
- [x] The table should scroll right and left on mobile, but stretch completely across the screen on desktop.
- [x] Add an event listener to the fish icon and progress bar for `'click'` events.
- [x] Create a function that calls the API and returns an `object` formatted as below.
`var acnhDataObj= {
  fish: {
    carp: {
      icon: '',
      image: '',
      price-reg: '',
      price-cj: '',
      location: '',
      time: '',
      shadow: '',
      season: '',
    }
  },
  bugs: {
    common_butterfly: {
      icon: '',
      image: '',
      price-reg: '',
      price-flick: '',
      location: '',
      time: '',
      shadow: '',
      season: '',
    }
  },
  sea: {
    seaweed: {
      icon: '',
      image: '',
      price-reg: '',
      speed: '',
      time: '',
      shadow: '',
      season: '',
    }
  },
  fossils: {
    icon: '',
    price-reg: ''
  },
  art: {
    icon: '',
    price-reg: ''
  }
}
  - [x] Define a new `function` "createCritterTable".
  - [x] Inside this function, using the data in the `acnhDataObject`, build the tables for each collection...
    - [x] One function is needed to create the DOM elements for each square --> should return one square.
    - [x] Another function is needed to iterate through the `acnhDataObj` and append those elements to the DOM.
    - [x] Make sure each square has a `[data-collection-id='itemName']` for later use.
- [x] Check that the display looks good on both mobile and desktop screens.
- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
