### ISSUE TITLE
User Can Interact with the Critterpedia

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/ajax-project#6]
## 💰 Motivation

Users will want to track their progress in the Critterpedia.

## 📐 Plan

On click of a creature in the Critterpedia, pull up that creatures information. Allow for toggle of 'caught' and update progress bar respectively.

## 🖼️ Wireframes

![user-can-edit-collections](https://user-images.githubusercontent.com/105157437/192400513-cfc78077-c727-48e2-ae82-a85c47dd136b.png)
![user-can-edit-collections-desktop](https://user-images.githubusercontent.com/105157437/192400512-0aa84204-3d11-4b4a-9641-c0138d1dba39.png)

## ✅ Task List

We need to create a collection object if one does not already exist and add it to storage to track our collection.

- [x] Modify the `renderCollection function` so that if a collection already exists for the clicked collection type in the collection data property of the data object, that collection data is used to render the collection instead of calling the API.
- [x] When the collection data objects are created in the 5 API calls, add the property `acquired` and set the value to the bool `false`.
- [x] Check to make sure that the page creates new collection objects in data.js for collections that do not exist, but builds a page with already existing data if collections do exist.

Next, we need to deal with interactivity. Hovering, clicking, and closing.

- [x] Add event listener to parent `ul slider-container` for hover events.
  - [x] On hover of a collection item, add a small circle with light green background and either ??? or collection item name depending on whether that item's `acquired` value is `true` or `false`.
- [x] Add event listener to parent `ul slider-container` for click events.
  - [x] On click of a collection item, open a `modal` in the center of the screen.
- [x] For the collection item modal...
  - [x] Create a dummy data box in the HTML to match the wireframe.
  - [x] For the "fish-collection", the 'Need a reference' text should link to the external image with shadow sizes.
  - [x] Create a `function` that updates the modal with the correct information from the clicked fish.
  - [x] Using the data from the `collection object`, fill in the appropriate data to the modal depending on collection item.
  - [x] Ensure the `modal` has a working close button. Clicking outside the modal should also close it.
- [x] Add an event listener to the "caught" `button` of the collection modal.
  - [x] On click, the value of the `acquired` property for that collection item should toggle from true --> false **or** from false --> true.
  - [x] The color should also change appropriately.
  - [x] Create a `function` that searches through the DOM for the currently opened collection item and removes the gray transparent cover from the image if `acquired: true` or adds the cover if `acquired: false`.
    - [x] Ensure this function is called every time the collection is loaded to update the collection.
    - [x] When doing so, this should also update the progress bars on both the collection screen and the home page with the current collection status.
- [x] Draw up modals for bug, sea, fossil, and art collections.
  - [x] Move unique time / location information into its own div for bug, sea, & fossil collections
  - [x] Move remaining info box information into its own div --> this is info unique to each collection.
  - [x] Create a `rendering function` for each collection that renders the appropriate info into the modal for that collection.
  - [x] Add logic to the collection `mouse-up event listener` (the one that listens for click equivalents) to render the correct collection type depending on type of item clicked. Use the `data.currentCollection` property & value to achieve this.
  - [x] Ensure that the caught button toggles the correct collection's `acquired` property

- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
