### ISSUE TITLE
User Can Delete Towns

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/ajax-project#7]
## 💰 Motivation

If a user decides that they no longer wish to keep a town, they should be able to delete it.

## 📐 Plan

Allow users to delete a town from its edit screen.

## 🖼️ Wireframes

![user-can-delete-a-town-mobile](https://user-images.githubusercontent.com/105157437/192400728-8b8607e7-6d93-4732-8f97-cd92123a85c0.png)
![user-can-delete-a-town-desktop](https://user-images.githubusercontent.com/105157437/192400726-a39cfaa2-8e6b-431a-b801-ad662f9279ea.png)

## ✅ Task List

- [x] Add a click target for deleting a town to the town-entry-form that only appears if the user is editing an entry.
- [x] Show a confirmation modal when the user clicks the Delete Entry click target.
- [x] Hide the modal if the user clicks Cancel.
- [x] Remove the entry from the data model and the town-entry DOM tree from the page if the user clicks Delete.
- [x] Show the towns list if the user clicks Delete.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
